from __future__ import annotations

import hashlib
import hmac
import json
import logging
from typing import Any

from fastapi import APIRouter, Request, HTTPException, status

from app.config import config
from app.graph.state import WorkflowState
from app.graph.workflow import AutoFixWorkflow
from app.integrations.git_auto_fixer import GitAutoFixer
from app.integrations.github_actions_logs import GitHubActionsLogFetcher
from app.integrations.github_pr_creator import GitHubPRCreator

logger = logging.getLogger(__name__)

router = APIRouter()

workflow = AutoFixWorkflow()
log_fetcher = GitHubActionsLogFetcher()
auto_fixer = GitAutoFixer()
pr_creator = GitHubPRCreator()


@router.post("/github/webhook")
async def github_webhook(request: Request) -> dict[str, Any]:
    secret = config.GITHUB_WEBHOOK_SECRET
    if not secret:
        logger.error("GITHUB_WEBHOOK_SECRET is not configured or is empty. Rejecting request.")
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Server configuration error: webhook secret is not configured"
        )

    signature_header = request.headers.get("X-Hub-Signature-256")
    if not signature_header:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Signature header X-Hub-Signature-256 is missing"
        )

    body = await request.body()

    expected = "sha256=" + hmac.new(
        secret.encode("utf-8"),
        body,
        hashlib.sha256,
    ).hexdigest()

    if not hmac.compare_digest(signature_header, expected):
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Invalid webhook signature"
        )

    try:
        payload = json.loads(body)
    except json.JSONDecodeError as e:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=f"Invalid JSON payload: {e}"
        )

    repo_full = payload.get("repository", {}).get("full_name")
    action = payload.get("action")
    ref = payload.get("ref")
    head_sha = payload.get("head_sha")

    workflow_run = payload.get("workflow_run", {})
    conclusion = workflow_run.get("conclusion")
    run_id = workflow_run.get("id")
    workflow_url = workflow_run.get("html_url")

    if action not in {"push", "pull_request", "check_suite", "workflow_run"}:
        return {"status": "ignored", "reason": "unsupported event"}

    if action == "workflow_run" and conclusion != "failure":
        return {"status": "no failure detected"}

    if not repo_full:
        return {"status": "invalid payload", "reason": "missing repository"}

    owner, repo = repo_full.split("/", 1)

    ci_log = log_fetcher.get_workflow_logs(owner, repo, run_id) if run_id else ""

    repo_url = f"https://github.com/{repo_full}"
    state = WorkflowState(
        repo_url=repo_url,
        ci_log=ci_log,
    )
    state.repo_context = {"repository": repo_full, "branch": ref, "commit_sha": head_sha, "workflow_url": workflow_url, "run_id": run_id}

    result = workflow.run(state)
    final_report = result.final_report

    fix_data: dict[str, Any] = {}
    if final_report is not None:
        fix_data = final_report.fix.model_dump() if getattr(final_report, "fix", None) else {}

    auto_pr_url: str | None = None
    if fix_data.get("confidence", 0) > 0.75:
        fix_result = auto_fixer.apply_fix_and_create_pr(repo_url, fix_data)
        if fix_result.get("status") == "pushed":
            root_cause = getattr(final_report, "root_cause", None)
            root_cause_text = getattr(root_cause, "cause", None) or (root_cause.get("cause") if isinstance(root_cause, dict) else "unknown")
            auto_pr_url = pr_creator.create_pr(
                repo_name=repo_full,
                branch_name=fix_result["branch"],
                title="AutoFix CI: Automated Repair",
                body=(
                    "This PR was automatically generated by AutoFix CI.\n\n"
                    f"Summary: {getattr(final_report, 'summary', 'Auto-fix attempt')}\n"
                    f"Root cause: {root_cause_text}"
                ),
            )

    return {
        "status": "processed",
        "repository": repo_full,
        "branch": ref,
        "commit_sha": head_sha,
        "workflow_url": workflow_url,
        "run_id": run_id,
        "result": final_report,
        "auto_pr": auto_pr_url,
    }